#Compose
services:
  php:
    build:
      context: .
      dockerfile: .docker/php/php.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}

    container_name: php
    user: "0:0"
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/expelliarmus
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.env:/var/www/expelliarmus/.env
    networks:
      - expelliarmus
    depends_on:
      - postgres
      - redis

  npm:
    build:
      context: .docker/node
      dockerfile: node.Dockerfile

    container_name: npm
    volumes:
      - ./frontend:/var/www/expelliarmus
    ports:
      - "3000:3000"
    command: [ "tail", "-f", "/dev/null" ]
    networks:
      - expelliarmus

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/nginx.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}

    container_name: nginx
    volumes:
      - ./frontend:/var/www/expelliarmus
    ports:
      - "8000:8000"
      - "8080:8080"
    depends_on:
      - php
      - npm
    networks:
      - expelliarmus

  postgres:
    container_name: postgres
    image: postgres:17.4-alpine
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
      - .docker/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "is_ready" ]
      timeout: 5s
      retries: 10
    networks:
      - expelliarmus

  #  supervisor:
  #    build:
  #      context: .docker/php
  #      dockerfile: supervisor.Dockerfile
  #    container_name: supervisor
  #    volumes:
  #      - .:/var/www/expelliarmus
  #    networks:
  #      - expelliarmus

  scheduler:
    build:
      context: .
      dockerfile: .docker/php/scheduler.Dockerfile

    container_name: scheduler
    volumes:
      - ./backend:/var/www/expelliarmus
    command: /bin/sh -c "/usr/sbin/crond -f -l 8"
    networks:
      - expelliarmus
    depends_on:
      - php

  queue:
    build:
      context: .
      dockerfile: .docker/php/queue.Dockerfile

    container_name: queue

    volumes:
      - ./backend:/var/www/expelliarmus
    command: /bin/sh -c "php artisan queue:work --queue=high,low --sleep=3 --tries=3"
    networks:
      - expelliarmus
    restart: always
    depends_on:
      - php
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - expelliarmus

networks:
  expelliarmus:
    driver: bridge

volumes:
  postgres: