services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/nginx.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: ghcr.io/artyom84783454/expelliarmus-market-nginx:latest
    container_name: nginx
    volumes:
      - ./backend:/var/www/expelliarmus/backend
      - ./frontend:/var/www/expelliarmus/frontend
    ports:
      - "80:80"  
    depends_on:
      - php
    networks:
      - expelliarmus
  php:
    build:
      context: .
      dockerfile: .docker/php/php.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: ghcr.io/artyom84783454/expelliarmus-market-php:latest
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/expelliarmus/backend
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.env:/var/www/expelliarmus/.env
    networks:
      - expelliarmus
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  postgres:
    container_name: postgres
    image: postgres:17.4-alpine
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
      - .docker/db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USERNAME" ]
      interval: 5s
      retries: 10
    networks:
      - expelliarmus
  scheduler:
    build:
      context: .docker/php
      dockerfile: scheduler.Dockerfile
    image: ghcr.io/artyom84783454/expelliarmus-market-scheduler:latest
    container_name: scheduler
    volumes:
      - .:/var/www/expelliarmus
    command: /bin/sh -c "/usr/sbin/crond -f -l 8"
    networks:
      - expelliarmus
    depends_on:
      - php
  queue:
    build:
      context: .docker/php
      dockerfile: queue.Dockerfile
    image: ghcr.io/artyom84783454/expelliarmus-market-queue:latest
    container_name: queue
    volumes:
      - .:/var/www/expelliarmus
    command: /bin/sh -c "php artisan queue:work --queue=high,low --sleep=3 --tries=3"
    networks:
      - expelliarmus
    restart: always
    depends_on:
      - php
      - redis
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10
    networks:
      - expelliarmus


networks:
  expelliarmus:
    driver: bridge

volumes:
  postgres:
